services:
  coinmarketcap-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinmarketcap-api
    environment:
      - CMC_API_KEY=${CMC_API_KEY:-fa1b6da457d3419d8ffccc2b52c789f1}
      - CRYPTO_IDS=${CRYPTO_IDS:-1,1027}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge